[server]
headless = true
enableCORS = false
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#0F4C81"

[global]
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[ui]
hideTopBar = true
